# Utiliser une image Python officielle comme image de base
FROM python:3.12-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier des exigences et installer les dépendances
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copier le reste du code de l'application
COPY . .

# Exposer le port utilisé par l'application
EXPOSE 8000

# Commande pour exécuter l'application
CMD ["gunicorn", "JeuxOlympiques.wsgi.application", "--bind", "0.0.0.0:8000"]